---

- name: Provision Web Server
  hosts: webservers
  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes
    
    - name: install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes
    